; API
amxx-modding-kit/api_assets.amxx debug
amxx-modding-kit/api_custom_entities.amxx debug
amxx-modding-kit/api_custom_weapons.amxx debug
amxx-modding-kit/api_shops.amxx debug
amxx-modding-kit/api_player_cosmetics.amxx debug
amxx-modding-kit/api_player_camera.amxx debug
amxx-modding-kit/api_player_model.amxx debug
amxx-modding-kit/weapon_base_throwable.amxx debug
amxx-modding-kit/entity_fire.amxx

; Core
snowwars/core/core.amxx debug
snowwars/core/gamerules.amxx debug
; snowwars/core/player_attributes.amxx debug
snowwars/core/player_artifacts.amxx debug
snowwars/core/shop.amxx debug
snowwars/core/bomb.amxx debug
snowwars/core/player.amxx debug

; Features
snowwars/features/fireworks.amxx debug

; Entities
snowwars/entities/snowball.amxx debug
snowwars/entities/item_artifact.amxx debug
snowwars/entities/fireworkrocket.amxx debug
snowwars/entities/fireworksbox.amxx debug
snowwars/entities/snowman.amxx debug
snowwars/entities/firework_effect.amxx debug
snowwars/entities/fireplace.amxx debug
snowwars/entities/weaponbox.amxx debug

; Weapons
snowwars/weapons/base_blueprint.amxx debug
snowwars/weapons/snowball.amxx debug
snowwars/weapons/slingshot.amxx debug
snowwars/weapons/fireworksbox.amxx debug
snowwars/weapons/snowman.amxx debug 
snowwars/weapons/shield.amxx debug
snowwars/weapons/hotdrink.amxx debug
snowwars/weapons/fireplace.amxx debug

; Artifacts
snowwars/artifacts/downjacket.amxx debug
snowwars/artifacts/lemonjuice.amxx debug

; Extra
snowwars/extra/bots_autobuy.amxx debug
