; API
api_assets.amxx debug
api_custom_entities.amxx debug
api_custom_weapons.amxx debug
api_shops.amxx debug
api_player_cosmetics.amxx debug
api_player_camera.amxx debug

; Core
snowwars.amxx debug
sw_gamerules.amxx debug
sw_player_attributes.amxx debug
sw_player_artifacts.amxx debug
sw_shop.amxx debug
sw_bomb.amxx debug
sw_player.amxx debug

; Entities
entity_sw_snowball.amxx debug
entity_sw_item_artifact.amxx debug
entity_sw_fireworkrocket.amxx debug
entity_sw_fireworksbox.amxx debug
entity_sw_snowman.amxx debug

; Weapons
weapon_base_throwable.amxx debug
weapon_sw_snowball.amxx debug
weapon_sw_slingshot.amxx debug
weapon_sw_fireworksbox.amxx debug
weapon_sw_snowman.amxx debug 

; Artifacts
sw_artifact_downjacket.amxx debug
sw_artifact_lemonjuice.amxx debug

; Bots
sw_bots_autobuy.amxx debug
