; API
amxx-modding-kit/api_assets.amxx
amxx-modding-kit/api_custom_entities.amxx
amxx-modding-kit/api_custom_weapons.amxx
amxx-modding-kit/api_shops.amxx
amxx-modding-kit/api_player_cosmetics.amxx
amxx-modding-kit/api_player_model.amxx
amxx-modding-kit/weapon_base_throwable.amxx
amxx-modding-kit/entity_fire.amxx

; Core
snowwars/core/core.amxx
snowwars/core/gamerules.amxx
snowwars/core/player_artifacts.amxx
snowwars/core/shop.amxx
snowwars/core/bomb.amxx
snowwars/core/player.amxx

; Features
snowwars/features/fireworks.amxx

; Entities
snowwars/entities/snowball.amxx
snowwars/entities/item_artifact.amxx
snowwars/entities/fireworkrocket.amxx
snowwars/entities/fireworksbox.amxx
snowwars/entities/snowman.amxx
snowwars/entities/firework_effect.amxx
snowwars/entities/fireplace.amxx
snowwars/entities/weaponbox.amxx

; Weapons
snowwars/weapons/base_blueprint.amxx
snowwars/weapons/snowball.amxx
snowwars/weapons/slingshot.amxx
snowwars/weapons/fireworksbox.amxx
snowwars/weapons/snowman.amxx 
snowwars/weapons/shield.amxx
snowwars/weapons/hotdrink.amxx
snowwars/weapons/fireplace.amxx

; Artifacts
snowwars/artifacts/downjacket.amxx
snowwars/artifacts/lemonjuice.amxx

; Extra
snowwars/extra/bots_autobuy.amxx
