#define SW_TITLE "Snow Wars"
#define SW_VERSION "0.9.2"

stock const SW_WEAPON_SNOWBALL[] = "snowwars/v090/weapon_snowball";
stock const SW_WEAPON_SLINGSHOT[] = "snowwars/v090/weapon_slingshot";
stock const SW_WEAPON_FIREWORKSBOX[] = "snowwars/v090/weapon_fireworksbox";
stock const SW_WEAPON_SNOWMAN[] = "snowwars/v100/weapon_snowman";

stock const SW_ARTIFACT_DOWNJACKET[] = "downjacket";
stock const SW_ARTIFACT_LEMONJUICE[] = "lemonjuice";

stock const SW_WEAPON_SNOWBALL_HUD_TXT[] = "sprites/snowwars/v090/weapon_snowball.txt";
stock const SW_WEAPON_SLINGSHOT_HUD_TXT[] = "sprites/snowwars/v090/weapon_slingshot.txt";
stock const SW_WEAPON_FIREWORKSBOX_HUD_TXT[] = "sprites/snowwars/v090/weapon_fireworksbox.txt";
stock const SW_WEAPON_SNOWMAN_HUD_TXT[] = "sprites/snowwars/v100/weapon_snowman.txt";

stock const SW_WEAPON_SNOWBALL_V_MODEL[] = "models/snowwars/v090/weapons/v_snowball.mdl";
stock const SW_WEAPON_SNOWBALL_P_MODEL[] = "models/snowwars/v090/weapons/p_snowball.mdl";
stock const SW_WEAPON_SNOWBALL_W_MODEL[] = "models/snowwars/v090/weapons/w_snowball.mdl";
stock const SW_WEAPON_SNOWBALL_LEMON_W_MODEL[] = "models/snowwars/v090/weapons/w_snowball_lemon.mdl";

stock const SW_WEAPON_SLINGSHOT_V_MODEL[] = "models/snowwars/v090/weapons/v_slingshot.mdl";
stock const SW_WEAPON_SLINGSHOT_P_MODEL[] = "models/snowwars/v090/weapons/p_slingshot.mdl";
stock const SW_WEAPON_SLINGSHOT_W_MODEL[] = "models/snowwars/v090/weapons/w_slingshot.mdl";

stock const SW_WEAPON_FIREWORKSBOX_V_MODEL[] = "models/snowwars/v090/weapons/v_fireworksbox.mdl";
stock const SW_WEAPON_FIREWORKSBOX_P_MODEL[] = "models/snowwars/v090/weapons/p_fireworksbox.mdl";
stock const SW_WEAPON_FIREWORKSBOX_W_MODEL[] = "models/snowwars/v090/weapons/w_fireworksbox.mdl";

stock const SW_WEAPON_SNOWMAN_V_MODEL[] = "";
stock const SW_WEAPON_SNOWMAN_P_MODEL[] = "";
stock const SW_WEAPON_SNOWMAN_W_MODEL[] = "models/snowwars/v100/weapons/w_snowman.mdl";

stock const SW_ARTIFACT_DOWNJACKET_W_MODEL[] = "models/snowwars/v090/artifacts/w_downjacket.mdl";
stock const SW_ARTIFACT_DOWNJACKET_P_MODEL[] = "models/snowwars/v090/artifacts/p_downjacket.mdl";

stock const SW_ARTIFACT_LEMONJUICE_W_MODEL[] = "models/snowwars/v090/artifacts/w_lemonsnow.mdl";

stock const SW_SOUND_SNOWBALL_THROW[] = "snowwars/v090/snowthrow1.wav";
stock const SW_SOUND_SNOWBALL_HIT[] = "snowwars/v090/sbhit.wav";
stock const SW_SOUND_SNOWBALL_LEMON_HIT[] = "debris/bustflesh1.wav";
stock const SW_SOUND_JINGLE_MUSIC[] = "snowwars/v090/christmas_jingle.wav";
stock const SW_SOUND_FIREWORK_ROCKET[] = "snowwars/v090/rocket1.wav";
stock const SW_SOUND_DOWNJACKET[] = "snowwars/v090/pw_shield.wav";
stock const SW_SOUND_PLAYER_SPAWN[] = "snowwars/v090/push.wav";
stock const SW_SOUND_RETURN[] = "snowwars/v100/return.wav";
stock const SW_SOUND_PLAYER_HIT[][] = { "snowwars/v090/snowhit_human1.wav", "snowwars/v090/snowhit_human2.wav" };

stock const SW_MODEL_SNOWMAN[] = "models/snowwars/v100/snowman.mdl";
